---
# This workflow uses actions that are not certified by GitHub. They are provided
# by a third-party and are governed by separate terms of service, privacy
# policy, and support documentation.

name: "Generate Go module endpoints"
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # https://crontab.guru/#*/30_*_*_*_*
    - cron: "*/30 * * * *"

defaults:
  run:
    shell: bash

env:
  DOCKER_BUILDKIT: 1

permissions: read-all

jobs:
  generate:
    runs-on: ubuntu-latest
    name: Generate the latest definitions
    permissions:
      contents: write # for Git to git push
      id-token: write
      pages: write
    timeout-minutes: 2
    strategy:
      fail-fast: false

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
        with:
          egress-policy: audit

      - name: Checkout the code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      # - uses: actions/setup-python@v6

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0

      - name: Generate
        id: generate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          uv run ./run.py

      - name: Git config
        run: |
          git config --global user.name "Northwood Labs Bot"
          git config --global user.email "bot@northwood-labs.com"
          git pull --rebase --autostash

      - name: Git commit
        run: |
          if [[ "$(git status -sb | wc -l)" == "1" ]]; then
            echo "No changes to commit."
          else
            git add .
            git commit -m "Automated commit: $(date +"%Y-%m-%dT%T%z")"
            git push origin main
          fi
